[nodes]
node1 ansible_host=10.0.0.89
node2 ansible_host=10.0.0.188
node3 ansible_host=10.0.0.254

[nodes:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3.12